# Generated by Django 5.2 on 2025-04-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0004_category_category2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category2',
            new_name='PerportyType',
        ),
    ]
